//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBill
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public int id { get; set; }
        public string number { get; set; }
        public string issue_date { get; set; }
        public string due_date { get; set; }
        public Nullable<int> company_details_id { get; set; }
        public Nullable<int> vendor_id { get; set; }
        public string vendor_name { get; set; }
        public string vendor_code { get; set; }
        public string vendor_email { get; set; }
        public string vendor_phone { get; set; }
        public string vendor_contact { get; set; }
        public string vendor_billing_address { get; set; }
        public string vendor_billing_zip { get; set; }
        public string vendor_billing_city { get; set; }
        public string vendor_shipping_address { get; set; }
        public string vendor_shipping_zip { get; set; }
        public string vendor_shipping_city { get; set; }
        public Nullable<bool> is_paid { get; set; }
        public Nullable<bool> is_draft { get; set; }
        public string total_no_tax { get; set; }
        public string total_tax { get; set; }
        public string total_all { get; set; }
        public string internal_notes { get; set; }
        public string bill_notes { get; set; }
        public string deleted { get; set; }
        public string color { get; set; }
        public string po_number { get; set; }
        public string logo { get; set; }
        public Nullable<int> page_size_id { get; set; }
        public Nullable<int> vendor_billing_state_id { get; set; }
        public Nullable<int> vendor_shipping_state_id { get; set; }
        public string pay_email { get; set; }
        public Nullable<bool> pay_online { get; set; }
        public Nullable<int> flag_id { get; set; }
        public int layout { get; set; }
        public string discount { get; set; }
        public Nullable<bool> sent { get; set; }
        public int print_id { get; set; }
        public string type { get; set; }
        public string fiscal_year { get; set; }
        public string number_prefix { get; set; }
        public string second_number { get; set; }
        public string excise_duty { get; set; }
        public Nullable<bool> use_transport { get; set; }
        public string delivery_note { get; set; }
        public string vehicle_number { get; set; }
        public string esugam { get; set; }
        public string lr_number { get; set; }
        public string shipping_method { get; set; }
        public string excise_cess { get; set; }
        public Nullable<bool> cancelled { get; set; }
        public Nullable<bool> quantity_no_decimal { get; set; }
        public Nullable<bool> product_inline_discount { get; set; }
        public string po_date { get; set; }
        public string gst_type { get; set; }
        public Nullable<int> supply_state_id { get; set; }
        public string discount_all { get; set; }
        public int lr_label { get; set; }
        public string transporter_id { get; set; }
        public Nullable<bool> inclusive_tax { get; set; }
        public int esugam_label { get; set; }
        public string transporter_name { get; set; }
        public string transporter_gstin { get; set; }
        public Nullable<bool> show_cess { get; set; }
        public Nullable<bool> reverse_charges { get; set; }
        public Nullable<int> shipping_tax_id { get; set; }
        public string invoice_number { get; set; }
        public Nullable<int> import_currency_id { get; set; }
        public string exchange_rate { get; set; }
        public Nullable<int> main_currency_id { get; set; }
        public string tax_source { get; set; }
        public int tax_source_type { get; set; }
        public Nullable<bool> tax_source_enabled { get; set; }
    }
}
