//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBill
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_vendor_conversions
    {
        public int id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> vendor_id { get; set; }
    }
}
