//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBill
{
    using System;
    using System.Collections.Generic;
    
    public partial class currency
    {
        public int id { get; set; }
        public string currency_symbol { get; set; }
        public string currency_name { get; set; }
        public Nullable<bool> is_used { get; set; }
        public string symbol { get; set; }
    }
}
