//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBill
{
    using System;
    using System.Collections.Generic;
    
    public partial class expense_products
    {
        public int id { get; set; }
        public string name { get; set; }
        public string measuring_unit { get; set; }
        public string price { get; set; }
        public string deleted { get; set; }
        public Nullable<int> tax_id { get; set; }
    }
}
