//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBill
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturi_stornate
    {
        public int id { get; set; }
        public Nullable<double> factura_id { get; set; }
        public string data_stornarii { get; set; }
        public string valoare1 { get; set; }
        public string valoare2 { get; set; }
    }
}
