//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBill
{
    using System;
    using System.Collections.Generic;
    
    public partial class fisc_year
    {
        public int id { get; set; }
        public string document_type { get; set; }
        public string start_number { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> reset_number_from_id { get; set; }
    }
}
