//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBill
{
    using System;
    using System.Collections.Generic;
    
    public partial class flag
    {
        public int id { get; set; }
        public bool value_with_tax { get; set; }
        public string invoice_label { get; set; }
        public string estimate_label { get; set; }
        public string product_label { get; set; }
        public string quantity_label { get; set; }
        public string price_label { get; set; }
        public Nullable<bool> show_address { get; set; }
        public Nullable<bool> total_without_decimals { get; set; }
        public Nullable<bool> total_in_words { get; set; }
        public Nullable<bool> show_signature { get; set; }
        public Nullable<int> shipping_price { get; set; }
        public Nullable<bool> replace_quantity { get; set; }
        public Nullable<bool> show_shipping { get; set; }
        public string shipping_label { get; set; }
        public Nullable<int> indian_format { get; set; }
        public Nullable<int> show_up_column { get; set; }
        public Nullable<int> decimals { get; set; }
        public Nullable<int> show_um_column { get; set; }
        public Nullable<int> show_tax_column { get; set; }
        public Nullable<int> show_tax_percentage { get; set; }
        public string excise_duty { get; set; }
        public Nullable<int> hide_amount { get; set; }
        public string um_label { get; set; }
        public string tax_label { get; set; }
        public Nullable<int> replace_paypal { get; set; }
        public string fisc_year_start { get; set; }
        public Nullable<bool> end_fisc_year { get; set; }
        public Nullable<bool> use_document_prefix { get; set; }
        public string prefix_separator { get; set; }
        public Nullable<bool> use_date_prefix { get; set; }
        public Nullable<int> show_delivery_note_amount { get; set; }
        public string po_number_label { get; set; }
        public Nullable<bool> odt_activated { get; set; }
        public Nullable<bool> use_pin_code { get; set; }
        public string tax_invoice_label { get; set; }
        public string retail_invoice_label { get; set; }
        public string excise_invoice_label { get; set; }
        public string proforma_label { get; set; }
        public string challan_label { get; set; }
        public Nullable<bool> show_contact_name { get; set; }
        public string copy_type_original { get; set; }
        public string copy_type_dupl { get; set; }
        public string copy_type_tripl { get; set; }
        public string copy_type_quadr { get; set; }
        public Nullable<bool> header_on_all_pages { get; set; }
        public Nullable<bool> show_net_received { get; set; }
        public Nullable<bool> a5_more_pages { get; set; }
        public Nullable<bool> use_second_number { get; set; }
        public Nullable<bool> change_dosc_df { get; set; }
        public Nullable<bool> basic_inventory { get; set; }
        public Nullable<bool> inventory_docs { get; set; }
        public Nullable<bool> rmv_product_qty_decimals { get; set; }
        public Nullable<bool> show_dn_tax { get; set; }
        public Nullable<bool> show_dn_price { get; set; }
        public Nullable<bool> show_gst_rates { get; set; }
        public Nullable<bool> show_total_tax { get; set; }
        public Nullable<bool> show_total_before_tax { get; set; }
        public Nullable<bool> split_calc_cgst { get; set; }
        public Nullable<bool> inclusive_tax { get; set; }
        public string client_note_label { get; set; }
        public Nullable<bool> hindi_keyboard { get; set; }
        public Nullable<bool> show_grand_total { get; set; }
        public Nullable<bool> fy_reset_numbering { get; set; }
        public string end_fiscal_year_date { get; set; }
        public string purchase_order_label { get; set; }
        public Nullable<bool> show_discount_column { get; set; }
        public string discount_label { get; set; }
    }
}
