//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBill
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public int id { get; set; }
        public long number { get; set; }
        public System.DateTime issue_date { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public Nullable<int> company_details_id { get; set; }
        public string client_id { get; set; }
        public string client_name { get; set; }
        public string client_code { get; set; }
        public Nullable<bool> is_paid { get; set; }
        public Nullable<bool> is_draft { get; set; }
        public string total_no_tax { get; set; }
        public string total_tax { get; set; }
        public string total_all { get; set; }
        public string invoice_notes { get; set; }
        public string deleted { get; set; }
        public string po_number { get; set; }
        public string delivery_note { get; set; }
        public Nullable<bool> cancelled { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<System.DateTime> po_date { get; set; }
    }
}
