//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBill
{
    using System;
    using System.Collections.Generic;
    
    public partial class packing_slip_products
    {
        public int id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> packing_slip_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string measuring_unit { get; set; }
        public string quantity { get; set; }
        public string ship_measuring_unit { get; set; }
        public string ship_quantity { get; set; }
    }
}
