//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBill
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_documents
    {
        public int id { get; set; }
        public string number { get; set; }
        public string client_name { get; set; }
        public string reference { get; set; }
        public string bank_charges { get; set; }
        public string type { get; set; }
        public string payment_type { get; set; }
        public string note { get; set; }
        public string pay_date { get; set; }
        public string amount_payment { get; set; }
        public string amount_used { get; set; }
        public string amount_excessed { get; set; }
        public string fiscal_year { get; set; }
        public string color { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> vendor_id { get; set; }
        public Nullable<int> flag_id { get; set; }
        public Nullable<int> company_details_id { get; set; }
        public Nullable<bool> sent { get; set; }
        public string logo { get; set; }
        public string deleted { get; set; }
        public Nullable<int> page_size_id { get; set; }
        public int layout { get; set; }
        public int print_id { get; set; }
        public Nullable<int> converted_payment_id { get; set; }
    }
}
