//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBill
{
    using System;
    using System.Collections.Generic;
    
    public partial class release_notes
    {
        public int id { get; set; }
        public string version { get; set; }
        public string year { get; set; }
        public string release_notes1 { get; set; }
        public Nullable<bool> show_notes { get; set; }
    }
}
