//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBill
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_tax_services
    {
        public int id { get; set; }
        public string service_category { get; set; }
        public string introduction_date { get; set; }
        public string deleted { get; set; }
        public string ac_tax_collection { get; set; }
        public string ac_other_receipts { get; set; }
        public string ac_deduct_refunds { get; set; }
        public string ac_education_cess { get; set; }
    }
}
