//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBill
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_history
    {
        public int id { get; set; }
        public Nullable<int> stock_id { get; set; }
        public string quantity { get; set; }
        public string description { get; set; }
        public string deleted { get; set; }
        public string added_date { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public Nullable<int> bill_id { get; set; }
        public Nullable<int> credit_note_id { get; set; }
        public string old_quantity { get; set; }
        public Nullable<int> debit_note_id { get; set; }
    }
}
