//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBill
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public int id { get; set; }
        public Nullable<int> product_id { get; set; }
        public string quantity { get; set; }
        public string deleted { get; set; }
        public string sold_quantity { get; set; }
        public string sold_total_amount { get; set; }
        public string cogs { get; set; }
        public string gross_margin { get; set; }
        public string gross_margin_percent { get; set; }
    }
}
