//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBill
{
    using System;
    using System.Collections.Generic;
    
    public partial class tax
    {
        public int id { get; set; }
        public string tax_name { get; set; }
        public double tax_percentage { get; set; }
        public Nullable<bool> is_default_tax { get; set; }
        public string deleted { get; set; }
        public string type { get; set; }
        public Nullable<bool> explicit_order { get; set; }
        public Nullable<bool> tax_on_taxable_value { get; set; }
    }
}
