//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBill
{
    using System;
    using System.Collections.Generic;
    
    public partial class tip
    {
        public int id { get; set; }
        public string text { get; set; }
        public Nullable<int> priority { get; set; }
        public Nullable<int> version { get; set; }
        public Nullable<int> count { get; set; }
    }
}
