//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBill
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpinvdata
    {
        public long id { get; set; }
        public Nullable<double> InvoiceValue { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string client_id { get; set; }
        public long number { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public System.DateTime issue_date { get; set; }
    }
}
